### ISSUE TITLE
Estructuración de pruebas

### ISSUE THREAD

**Issue by W3Edd** [Amigos-Informaticos/Loteria#41]
Hasta ahora, todas las pruebas que hemos hecho en Unity son pruebas unitarias. Pero eventualmente tendremos que hacer algunas pruebas de integración. Creo que incluso, podemos crear pruebas que interactúen directamente con las escenas.
Para estas pruebas futuras, deberíamos cambiar la estructura de directorios del proyecto en la sección de pruebas.
¿Qué les parece algo así?
Assets/
├─ Test/
│  ├─ Unit Testing/
│  ├─ Integration Testing/
│  ├─ InGame Testing/

**Comment by EfrainArenas** [comment]
A mí me parece una buena idea
